import type { Connector } from "./types";

export const seedCatalog: Connector[] = [
  {
    id: "interac-in",
    name: "Interac e-Transfer in",
    rail: "interac",
    direction: "in",
    audience: "human",
    holdMode: "pending_risk",
    kycMin: "T1",
    licensedParty: "KOHO",
    color: "green",
    status: "design",
    experimental: false,
    feeCopy: "Partner limits apply",
    etaCopy: "Minutes when Autodeposit is live",
    cancelRightsCopy: "Sender may cancel until accepted",
  },
  {
    id: "zum-rails",
    name: "Zum Rails",
    rail: "processor",
    direction: "both",
    audience: "developer",
    holdMode: "transit",
    kycMin: "T2",
    licensedParty: "",
    color: "yellow",
    status: "design",
    experimental: false,
    feeCopy: "Quoted by vendor",
    etaCopy: "Rail-dependent",
    cancelRightsCopy: "Vendor + sponsor rules",
  },
  {
    id: "helcim",
    name: "Helcim",
    rail: "card",
    direction: "in",
    audience: "developer",
    holdMode: "pending_risk",
    kycMin: "T3",
    licensedParty: "",
    color: "yellow",
    status: "design",
    experimental: false,
    feeCopy: "Processor schedule",
    etaCopy: "After processor settlement",
    cancelRightsCopy: "Chargeback window",
  },
  {
    id: "trolley",
    name: "Trolley",
    rail: "payout_card",
    direction: "out",
    audience: "business",
    holdMode: "transit",
    kycMin: "T3",
    licensedParty: "",
    color: "yellow",
    status: "design",
    experimental: false,
    feeCopy: "Payout schedule",
    etaCopy: "Vendor SLA",
    cancelRightsCopy: "Once sent, rail rules",
  },
  {
    id: "xtm",
    name: "XTM",
    rail: "processor",
    direction: "both",
    audience: "business",
    holdMode: "stored",
    kycMin: "T3",
    licensedParty: "",
    color: "red",
    status: "off",
    experimental: false,
    feeCopy: "N/A",
    etaCopy: "N/A",
    cancelRightsCopy: "Refused",
  },
];
